In [1]:
import pandas as pd 
import numpy as np

In [2]:
df= pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Study Session with Naomi\dirty_cafe_sales.csv")

In [3]:
df.head(12)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR

In [4]:
df.shape

(10000, 8)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [6]:
df.duplicated().sum()

0

In [7]:
df=df.drop_duplicates()

In [8]:
df["Transaction Date"]= pd.to_datetime(df["Transaction Date"], errors="coerce")

In [9]:
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce").astype("Int64")

In [10]:
cols=["Total Spent","Price Per Unit"]
df[cols]=df[cols].apply(pd.to_numeric, errors="coerce")

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9521 non-null   Int64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: Int64(1), datetime64[ns](1), float64(2), object(4)
memory usage: 634.9+ KB

In [12]:
df.columns=(df.columns
            .str.lower()
            .str.strip()
            .str.replace(" ", "_", regex=False)
            .str.replace(r"[^\w]", "", regex=True))

In [13]:
df.head(100)

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
95,TXN_8268061,Salad,3,5.0,15.0,ERROR,Takeaway,2023-08-20
96,TXN_5220895,Salad,5,5.0,25.0,Cash,In-store,2023-06-10
97,TXN_3085509,Coffee,4,2.0,8.0,Digital Wallet,In-store,2023-04-15
98,TXN_9999113,Juice,4,3.0,12.0,Cash,Takeaway,2023-05-27
99,TXN_8779771,Coffee,4,2.0,8.0,Cash,In-store,2023-07-25

In [14]:
#calculate Q1, Q3 and IQR
Q1 =df["total_spent"].quantile(0.25)
Q3 =df["total_spent"].quantile(0.75)
IQR = Q3-Q1
print(IQR)

8.0

In [15]:
#Define boundaries 
lower_bound =Q1-(1.5*IQR)
upper_bound =Q3+ (1.5*IQR)

In [16]:
outliers=df[(df["total_spent"]<lower_bound)|(df["total_spent"]>upper_bound)]
print(outliers)

     transaction_id     item  quantity  price_per_unit  total_spent  \
10      TXN_2548360    Salad         5             5.0         25.0
51      TXN_6342161    Salad         5             5.0         25.0
52      TXN_8914892  UNKNOWN         5             5.0         25.0
96      TXN_5220895    Salad         5             5.0         25.0
100     TXN_9517146      NaN         5             5.0         25.0
...             ...      ...       ...             ...          ...
9791    TXN_1232346    Salad         5             5.0         25.0
9805    TXN_9506076    Salad         5             5.0         25.0
9879    TXN_6393305    Salad         5             5.0         25.0
9908    TXN_8922585    Salad         5             5.0         25.0
9971    TXN_6120851    Salad         5             5.0         25.0

      payment_method  location transaction_date
10              Cash  Takeaway       2023-11-07
51             ERROR  Takeaway       2023-01-08
52    Digital Wallet       NaN       2023-03-15
96              Cash  In-store       2023-06-10
100             Cash  Takeaway       2023-10-30
...              ...       ...              ...
9791  Digital Wallet  In-store       2023-01-04
9805             NaN       NaN       2023-01-17
9879  Digital Wallet  In-store       2023-10-19
9908     Credit Card   UNKNOWN       2023-06-22
9971            Cash  Takeaway       2023-02-04

[259 rows x 8 columns]

In [17]:
for col in df.columns:
    print(f"\n{col}")
    print(df[col].value_counts(dropna=False))

transaction_id
transaction_id
TXN_1961373    1
TXN_4831525    1
TXN_1228927    1
TXN_6486912    1
TXN_3447069    1
              ..
TXN_5680238    1
TXN_7766134    1
TXN_2617257    1
TXN_8993132    1
TXN_6170729    1
Name: count, Length: 10000, dtype: int64

item
item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64

quantity
quantity
5       2013
2       1974
4       1863
3       1849
1       1822
<NA>     479
Name: count, dtype: Int64

price_per_unit
price_per_unit
3.0    2429
4.0    2331
2.0    1227
5.0    1204
1.0    1143
1.5    1133
NaN     533
Name: count, dtype: int64

total_spent
total_spent
6.0     979
12.0    939
3.0     930
4.0     923
20.0    746
15.0    734
8.0     677
10.0    524
NaN     502
2.0     497
9.0     479
5.0     468
16.0    444
25.0    259
7.5     237
1.0     232
4.5     225
1.5     205
Name: count, dtype: int64

payment_method
payment_method
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

location
location
NaN         3265
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

transaction_date
transaction_date
NaT           460
2023-02-06     40
2023-06-16     40
2023-03-13     39
2023-07-21     39
             ...
2023-04-27     15
2023-11-24     15
2023-03-11     14
2023-02-17     14
2023-07-22     14
Name: count, Length: 366, dtype: int64

In [18]:
df["item"].unique()[:20]

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

In [19]:
bad_values = ["UNKNOWN", "ERROR", ""]
df= df[~df["item"].isin(bad_values) & df["item"].notna()]

In [20]:
df["item"].unique()[:20]

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'Sandwich',
       'Juice', 'Tea'], dtype=object)

In [31]:
df[df["total_spent"].isna()]

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
65,TXN_4987129,Sandwich,3,<NA>,<NA>,NaN,In-store,2023-10-20
236,TXN_8562645,Salad,1,5.0,<NA>,NaN,In-store,2023-05-18
278,TXN_3229409,Juice,1,3.0,<NA>,Cash,Takeaway,2023-04-15
641,TXN_2962976,Juice,1,3.0,<NA>,NaN,NaN,2023-03-17
738,TXN_8696094,Sandwich,1,4.0,<NA>,NaN,Takeaway,2023-05-14
1674,TXN_9367492,Tea,2,<NA>,<NA>,Cash,In-store,2023-06-19
2229,TXN_8498613,Sandwich,2,<NA>,<NA>,NaN,NaN,2023-11-08
2585,TXN_1259340,Tea,3,<NA>,<NA>,Digital Wallet,NaN,2023-02-24
2796,TXN_9188692,Cake,1,3.0,<NA>,Credit Card,NaN,2023-12-01
3162,TXN_3577949,Cake,3,<NA>,<NA>,ERROR,Takeaway,2023-04-25
3203,TXN_4565754,Smoothie,1,4.0,<NA>,Digital Wallet,Takeaway,2023-10-06
3224,TXN_6297232,Coffee,1,2.0,<NA>,NaN,NaN,2023-04-07
3401,TXN_3251829,Tea,1,1.5,<NA>,Digital Wallet,In-store,2023-07-25
3598,TXN_2857444,Smoothie,1,<NA>,<NA>,Cash,Takeaway,2023-05-10
3673,TXN_6500126,Smoothie,2,<NA>,<NA>,NaN,UNKNOWN,NaT
4021,TXN_6424202,Cookie,2,<NA>,<NA>,Credit Card,In-store,2023-11-20
4257,TXN_6470865,Coffee,1,2.0,<NA>,Digital Wallet,Takeaway,2023-09-18
5841,TXN_5884081,Cookie,1,1.0,<NA>,Digital Wallet,In-store,2023-07-05
7029,TXN_4628338,Coffee,1,2.0,<NA>,Cash,NaN,2023-12-25
7035,TXN_8872984,Salad,5,<NA>,<NA>,Credit Card,In-store,2023-08-23
7230,TXN_5118799,Cookie,2,<NA>,<NA>,Cash,Takeaway,2023-04-23
7244,TXN_2253622,Sandwich,5,<NA>,<NA>,Digital Wallet,Takeaway,2023-09-30
7297,TXN_9944500,Smoothie,1,4.0,<NA>,Cash,In-store,2023-01-03
7568,TXN_3705445,Cookie,5,<NA>,<NA>,Cash,In-store,2023-09-13
7686,TXN_6905143,Coffee,5,<NA>,<NA>,Cash,ERROR,2023-08-09
8021,TXN_2428781,Salad,1,5.0,<NA>,NaN,In-store,2023-05-09
8128,TXN_6105807,Smoothie,3,<NA>,<NA>,Credit Card,Takeaway,2023-01-18
8443,TXN_2023651,Sandwich,1,4.0,<NA>,Cash,In-store,2023-05-25
8465,TXN_9669616,Coffee,1,2.0,<NA>,NaN,ERROR,2023-06-03
8479,TXN_1547245,Sandwich,1,4.0,<NA>,NaN,Takeaway,2023-09-11
8497,TXN_1525583,Sandwich,3,<NA>,<NA>,Cash,Takeaway,2023-05-20
8574,TXN_2546684,Juice,1,3.0,<NA>,Digital Wallet,Takeaway,2023-04-08
8732,TXN_4550558,Cookie,1,1.0,<NA>,Credit Card,In-store,2023-08-04
9212,TXN_7322317,Tea,1,<NA>,<NA>,NaN,NaN,2023-03-16
9590,TXN_9924732,Sandwich,1,4.0,<NA>,Credit Card,In-store,2023-01-18
9869,TXN_1975184,Coffee,1,2.0,<NA>,Digital Wallet,NaN,2023-01-15
9893,TXN_3809533,Juice,2,<NA>,<NA>,Digital Wallet,Takeaway,2023-02-02

In [32]:
mask= df["quantity"].isna() & df["price_per_unit"].notnull() & df["total_spent"].notnull()
df.loc[mask, "quantity"]= (df["total_spent"]/ df["price_per_unit"])

In [30]:
df["quantity"]=df["quantity"].fillna(1)

In [39]:
df["price_per_unit"] =df["price_per_unit"].fillna(df.groupby("item")["price_per_unit"].transform("median"))

In [40]:
mask= df["total_spent"].isna()
df.loc[mask, "total_spent"] = (df.loc[mask, "price_per_unit"]* df.loc[mask, "quantity"])

In [41]:
df[df["total_spent"].isna()]

Empty DataFrame
Columns: [transaction_id, item, quantity, price_per_unit, total_spent, payment_method, location, transaction_date]
Index: []

In [42]:
df.to_csv(r"C:\Users\HP\OneDrive\Desktop\Study Session with Naomi\Cleaned_cafe_sales.csv")